# Generated by Django 6.0 on 2025-12-28 08:40

import feed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_is_active_post_locker_id_and_more'),
    ]

    operations = [
        
    ]
