# Generated by Django 6.0 on 2025-12-11 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_post_author_quizquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='locker_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('locker_id', ''), _negated=True)), fields=('locker_id',), name='unique_active_locker'),
        ),
    ]
