# Generated by Django 6.0 on 2025-12-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_passcode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_active_locker',
        ),
    ]
