# Generated by Django 6.0 on 2026-01-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_post_unique_active_locker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locker_id', models.CharField(max_length=10, unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('trigger_unlock', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='locker_id',
        ),
        migrations.AddField(
            model_name='post',
            name='locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='feed.locker'),
        ),
    ]
